sudo: required
services:
    - docker
    
    
before_install:
    - docker build -t jacobkhoza/react-test -f./client/Dockerfile.dev ./client
    
scripts:
    - docker run -e CI=true jacobkhoza/react-test npm test
    
    
after_success:
    - docker build -t jacobkhoza/multi-client ./client
    - docker build -t jacobkhoza/multi-nginx ./nginx
    - docker build -t jacobkhoza/multi-server ./server
    - docker build -t jacobkhoza/multi-worker ./worker
    #Log in to the docker CLI
    - echo "${DOCKER_PASSWORD}" | docker login -u "$DOCKER_ID" --password-stdin
    
    #Take those images and push them to the docker hub
    - docker push jacobkhoza/multi-client
    - docker push jacobkhoza/multi-nginx
    - docker push jacobkhoza/multi-server
    - docker push jacobkhoza/multi-worker
